### ISSUE TITLE
Hook up form fields

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#2]
The form at /new/ needs to have the First Name, Last Name and Upload fields hooked up. I've hard-coded them here so I could style them. Originally it was just email address. Those fields should be output into the database and admin area so they can be exported after the promo is over. (the default admin login creds are in the readme and should probably be changed.)

The upload field should accept pdf and image files only I guess (png, gif, jpg, etc)

**Comment by cbradshaw** [comment]
Also, John mentioned connecting file uploads to Amazon S3 Bucket maybe. Is that required? This thing will be up for about one week so can the heroku server handle the files? Which is cheaper/easier to develop? Also want to make sure it will handle the potential traffic of course. Client expects HEAVY, HEAVY traffic though that will remain to be seen.

**Comment by jchapin** [comment]
If there's an upload, then S3 has to get involved. Heroku storage is ephemeral, because they may spin up a server running your application on a server anywhere they like... so only core application assets can be served directly from Heroku. Otherwise the next instance that Heroku spins up won't have any of the items stored on the last instance.

**Comment by jchapin** [comment]
Bucket policy in place, will send the environment variable config on Slack:

```
{
  "Id": "Policy1455826192404",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1455826189621",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::prelaunchr-for-ni/*",
      "Principal": {
        "AWS": [
          "arn:aws:iam::545886763795:user/NashvilleInteractive"
        ]
      }
    }
  ]
}
```

**Comment by jchapin** [comment]
Sent. @RanSolo in order to support uploading file to S3 you'll need to implement the Paperclip gem. We've used that on all the Spree projects, Milligram, and even Vertical Universe back in the day. There's a recent PR where that was added to Milligram by @drewmoore. Look at that for reference, but you should be able to knock that one out.
